/* eslint-disable no-unused-vars */
export enum pokemonTypes {
  SET_CURRENT_REQUEST = 'SET_CURRENT_REQUEST',
  FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST',
  FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS',
  FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE'
}
